FROM postgres:latest

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=S.d.a.p1
ENV POSTGRES_DB=postgres

# if you want to check the result on local
EXPOSE 5432

COPY ./init_db/init.sql /docker-entrypoint-initdb.d/