dbt_project:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: S.d.a.p1
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbt_workfile:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: S.d.a.p1
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
